@host=http://localhost
@port={{$dotenv PORT}}
@baseURL={{host}}:{{port}}

###
# @name getScreenShot
GET {{baseURL}}/

###
# @name print
GET {{baseURL}}/print

###
# @name health
GET {{baseURL}}/health
